### ISSUE TITLE
Prototype naar HTML review 

### ISSUE THREAD

**Issue by Clarice-COD** [halima98/the-client-website#1]
- De site staat nog niet online
- Gebruik h2-h6
- Schrijf meer comments bij je html
- Overzichtelijk

**Comment by Robinwouterson** [comment]
Review!

Prototype in HTML:

- De website (zonder css) is logisch en duidelijk opgezet, maar het ontbreekt aan bruikbaarheid door bijv. te weinig knoppen, links en  ontbrekende header en footer tags. Maar misschien is dat ook niet de bedoeling gezien de sitenog niet af is. 

- De juiste HTML elementen zijn gebruikt.

Prototype ontwerp:

- de gehele pagina is naar redelijkheid vormgeven
- het ontwerp is responsive
- validator.w3.org: nog niet kunnen beoordelen, site staat niet live.

Visuele Hiërarchie:
De grootte, vorm en positie zijn op orde. Er moet nog meer content komen om te kunnen beoordelen op bijv. de witruimte.
